# Generated by Django 3.0.8 on 2020-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='language_1',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='language_2',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='language_3',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='language_4',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='language_5',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='community',
            field=models.TextField(default='Built a COVID-19 precatuionary awareness website with 3 of my school friends.'),
            preserve_default=False,
        ),
    ]
